FROM maven:3.8.4-openjdk-11-slim as build
RUN mkdir registration
WORKDIR /registration
COPY ./ ./
RUN mvn clean package spring-boot:repackage

FROM adoptopenjdk/openjdk11:alpine-jre
COPY --from=build /registration/target/*.jar /jar-files/registration.jar
WORKDIR /jar-files

RUN apk --no-cache add curl

RUN apk add --no-cache openssl

ENV WAIT_VERSION 2.7.2
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/$WAIT_VERSION/wait /wait
RUN chmod +x /wait

EXPOSE 8761
CMD ["java", "-server", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseContainerSupport", "-jar", "registration.jar"]