version: '3.7'
services:
  postgres:
    container_name: postgres_db
    image: 'postgres:alpine'
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=compte_db
    logging:
      options:
        max-size: 10m
        max-file: '3'
    ports:
      - '5438:5432'
    volumes:
      - '../postgres-data:/var/lib/postgresql/data'
      #- './video.sql:/docker-entrypoint-initdb.d/video.sql'
    networks:
      - spring-network
  spring-app:
    container_name: compteService
    build: ./docker/compteService/
    #environment:
    #  - SPRING_PROFILES_ACTIVE=prod
    ports:
      - 8080:8080
    networks:
      - spring-network
networks:
  spring-network:
    driver: bridge
    name: spring-network