FROM maven:3.8.4-openjdk-11-slim as build
RUN mkdir gateway
WORKDIR /gateway
COPY ./ ./
RUN mvn clean package spring-boot:repackage
RUN ls
RUN ls ./target

FROM adoptopenjdk/openjdk11:alpine-jre

COPY --from=build /gateway/target/*.jar /jar-files/gateway.jar
WORKDIR /jar-files

RUN apk add --no-cache openssl

ENV WAIT_VERSION 2.7.2
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/$WAIT_VERSION/wait /wait
RUN chmod +x /wait

EXPOSE 9999
CMD ["java", "-server", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseContainerSupport", "-jar", "gateway.jar"]