  - hosts: swarm-master
    tasks:
    - name: Install git
      apt:
        name:
          - git
        state: present
        update_cache: yes
    - name: Clone a github repository
      git:
        repo: https://github.com/Thomas-Lacomblez/microservices-ensitech
        dest: /microservices/
        version: deploy
        clone: yes
        update: yes
    - name: Clone a github repository
      shell: "cd /microservices/ && docker stack deploy -c docker-compose-swarn.yml my_app"
