  - hosts: all
    become: yes
    become_user: root
    become_method: sudo
    tasks:
    - name: Install git, python 3.8
      apt:
        name:
          - git
        state: present
        update_cache: yes
    - name: Clone a github repository
      git:
        repo: https://github.com/Thomas-Lacomblez/microservices-ensitech
        dest: /microservices/
        version: deploy
        clone: yes
        update: yes
    - name: Clone a github repository
      shell: "cd /microservices && docker stack deploy -c docker-compose-swarn.yml my_app"